### ISSUE TITLE
Please make it possible to suppress "Exception in thread" msgs that clutter stdout

### ISSUE THREAD

**Issue by haku** [peplin/pygatt#264]
The `BGAPIBackend` class creates a thread using `threading.Thread(target=self._receive)` to handle receiving packets.  When periodically reading data from a BT sensor it occasionally errors out.  This is not a problem, the request can be retried, but in the process the receiver thread crashes and the Python `Thread` class dumps a long message to the console, e.g.:

```
Exception in thread Thread-10:
Traceback (most recent call last):
    File "/home/pi/.local/lib/python3.7/site-packages/serial/serialposix.py", line 501, in read
        'device reports readiness to read but returned no data '
    serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
        File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
            self.run()
          File "/usr/lib/python3.7/threading.py", line 865, in run
            self._target(*self._args, **self._kwargs)
          File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/bgapi/bgapi.py", line 647, in _receive
            packet = self._lib.parse_byte(self._ser.read())
          File "/home/pi/.local/lib/python3.7/site-packages/serial/serialposix.py", line 509, in read
            raise SerialException('read failed: {}'.format(e))
            serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

Since this is written by a `print()` statement it can not be suppressed by adjusting logging levels.  Could you please add a try-except block to `BGAPIBackend._receive()` and handle the `SerialException` exception before it reaches the `Thread` class?  This will make program output tidier.  Thanks!

**Comment by peplin** [comment]
Hey Haku, I'd gladly merge a PR for this.
