### ISSUE TITLE
Problem reading characteristics

### ISSUE THREAD

**Issue by mattie47** [peplin/pygatt#295]
I'm using pygatt to read ~ 30 characteristics. I find occasionally I have issues reading them, with the following trace:

```python
Traceback (most recent call last):
  File "./device-fleet.py", line 171, in <module>
    rawValue = device.char_read(deviceUuid.deviceUUID["value"])
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/device.py", line 17, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/device.py", line 40, in char_read
    return self._backend.char_read(self, uuid, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 50, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 593, in char_read
    self.sendline('char-read-uuid %s' % uuid)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
    self.wait(event, timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
    raise NotificationTimeout()
pygatt.exceptions.NotificationTimeout: None
```

I see `raise NotificationTimeout()` at the bottom, but I'm not subscribing to any notifications. It's unclear (my python skills aren't the best) to me why this issue is occurring. 

I do find with a few time.sleep(0.5) through the polling of the UUID list normally improves stability, but it would be nice to know why this is occurring.

Thanks,

Matt

**Comment by peplin** [comment]
The `NotificationTimeout` exception is a bit poorly named. It's raised when notifications time out, but also when other expected asynchronous events (e.g. waiting for a char read to return) time out. 

In this case, the full debug log may have more information about the data (if any) returned by the device when this read time outs. If I had to guess, there may be a bug in reading the output from `gatttool`. This backend is finicky since it's parsing text from a CLI program. If you're still having issues and can share a debug log, I can take a look (https://github.com/peplin/pygatt#debugging).
