### ISSUE TITLE
Embedded Linux board errors out like this

### ISSUE THREAD

**Issue by maneesh-phy** [peplin/pygatt#328]
```
>>> import pygatt
>>> adapter = pygatt.GATTToolBackend(search_window_size=2048)
>>> adapter.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/pygatt/backends/gatttool/gatttool.py", line 264, in start
    self.reset()
  File "/usr/lib/python3.5/site-packages/pygatt/backends/gatttool/gatttool.py", line 631, in reset
    subprocess.Popen(["sudo", "systemctl", "restart", "bluetooth"]).wait()
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo'
```

**Comment by peplin** [comment]
Hey @maneesh-phy , `sudo` is required if you are using the `gatttool` backend: https://github.com/peplin/pygatt/blob/master/pygatt/backends/gatttool/gatttool.py#L252

I'm adding this to th e docs in #329 to make that information easier to find. 

It looks like your embedded board does not have the `sudo` tool. If you are already running as root, you may be able to modify the backend code to check for that and skip the `sudo`. I'd merge a PR with that change, if you are so inclined. Thanks for filing the report.
